<?php
namespace app\admin\controller;

class Index extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $this->redirect('mp/mp/index');
    }

    /**
     * set page width mode
     * @author: fudaoji<fdj@kuryun.cn>
     */
    public function setScreen()
    {
        if (cookie('screen_size')) {
            cookie('screen_size', null);
        } else {
            cookie('screen_size', 1);
        }
    }
}
