<?php
namespace app\admin\controller;

class Index extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $this->redirect('mp/mp/index');
    }
}
