<?php
// +----------------------------------------------------------------------
// | [KyPHP System] Copyright (c) 2020 http://www.kuryun.com/
// +----------------------------------------------------------------------
// | [KyPHP] 并不是自由软件,你可免费使用,未经许可不能去掉KyPHP相关版权
// +----------------------------------------------------------------------
// | Author: fudaoji <461960962@qq.com>
// +----------------------------------------------------------------------
/**
 * Created by PhpStorm.
 * Script Name: Index.php
 * Create: 2020/3/1 12:11
 * Description: 首页
 * Author: fudaoji<fdj@kuryun.cn>
 */

namespace app\mp\controller;


class Index extends Base
{
    /**
     * @var \think\Model;
     */
    private $mpFollowM;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->mpFollowM = model('mpFollow');
    }

    /**
     * 公众号统计
     * @return mixed
     * @author: fudaoji<fdj@kuryun.cn>
     */
    public function index(){
        $assign = ['statics' => $this->mpFollowM->getReport($this->mpId)];
        return $this->show($assign);
    }
}