<?php
// +----------------------------------------------------------------------
// | [KyPHP System] Copyright (c) 2020 http://www.kuryun.com/
// +----------------------------------------------------------------------
// | [KyPHP] 并不是自由软件,你可免费使用,未经许可不能去掉KyPHP相关版权
// +----------------------------------------------------------------------
// | Author: fudaoji <461960962@qq.com>
// +----------------------------------------------------------------------
/**
 * Created by PhpStorm.
 * Script Name: ${FILE_NAME}
 * Create: 2020/3/1 12:11
 * Description: 
 * Author: fudaoji<fdj@kuryun.cn>
 */

namespace app\mp\controller;
use think\Validate;


class Index extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * delete mp
     * @param int $id
     * @author: fudaoji<fdj@kuryun.cn>
     */
    public function delMp($id = 0)
    {
        if (!$mp = model('mp')->getOneByMap(['id' => $id, 'user_id' => $this->adminId])) {
            $this->error('没有此公众号');
        }
        if(model("mp")->delOne($mp['id'])){
            //delete setting
            $data = model("setting")->getOneByMap(['mpid' => $id]);
            if($data){
                model("setting")->delOne($data['id']);
            }
            $this->success("操作成功");
        }
        $this->error('操作失败，请刷新重试');
    }

    /**
     * create mp
     * @return mixed
     * @author: fudaoji<fdj@kuryun.cn>
     */
    public function addMp()
    {
        if (request()->isAjax()) {
            $data = input('post.');
            unset($data['image']);
            $validate = new Validate(
                [
                    'name' => 'require',
                    'appid' => 'require',
                    'appsecret' => 'require',
                    'logo' => 'require',
                    'qrcode' => 'require',
                ],
                [
                    'name.require' => '公众号名称不能为空',
                    'appid.require' => ' Appid不能为空',
                    'appsecret.require' => 'Appsecret不能为空',
                    'logo.require' => 'Logo不能为空',
                    'qrcode.require' => '二维码不能为空',
                ]
            );
            $result = $validate->check($data);
            if ($result === false) {
                $this->error($validate->getError());
            }
            if(model('mp')->getOneByMap(['appid' => $data['appid']])){
                $this->error("该公众号已存在，请勿重复添加");
            }

            $data['user_id'] = $this->adminId;
            $data['valid_token'] = get_rand_char(32);
            $data['token'] = get_rand_char('32');
            $data['encodingaeskey'] = get_rand_char('43');

            $mp = model('mp')->addOne($data);
            if ($mp) {
                $json = json_encode([
                    'register_type'=>2,
                    'verify'=>0,
                    'up_score'=>0,
                    'up_money'=>0,
                    'keyword'=>'',
                    'picurl'=>'/static/imgs/def.jpg',
                    'ispwd'=>1,
                    'redirect_url'=>''
                ]);
                if ($setting = model("setting")->getOneByMap(['mpid' => $mp['id'], 'name' => 'register', 'cate'=>'mp'])) {
                    model("setting")->updateOne(['id' => $setting['id'], 'value' => $json]);
                } else {
                    model("setting")->addOne(['mpid' => $mp['id'], 'name' => 'register', 'cate'=>'mp', 'value' => $json]);
                }
                $this->success("操作成功", url("mp/index/mplist"));
            } else {
                $this->error('操作失败, 请刷新重试');
            }
        }
        return $this->show();
    }

    /**
     * 接入信息
     * @param int $mid
     * @return mixed
     * @author: fudaoji<fdj@kuryun.cn>
     */
    public function index($mid = 0)
    {
        $mp = model('mp')->getOneByMap(['id' => $mid, 'user_id' => $this->adminId]);
        if(empty($mp)){
            $this->error("公众号不存在");
        }
        $mp['url'] = request()->domain() . url('mp/entr/index', ['mid' => $mid]);
        return $this->show(['mp' => $mp]);
    }

    /**
     * update mp info
     * @param int $id
     * @return \think\response\View
     * Author: fudaoji<fdj@kuryun.cn>
     */
    public function updateMp($id = 0)
    {
        if (request()->isAjax()) {
            $data = input('post.');
            $mp = model('mp')->getOne($data['id']);
            if($mp && $mp['user_id'] == $this->adminId){
                if(model('mp')->updateOne($data)){
                    $this->success('操作成功', url('mp/index/mplist'));
                }else{
                    $this->error("操作失败，请刷新重试");
                }
            }else{
                $this->error("非法操作");
            }

        } else {
            if (!$mp = model('mp')->getOneByMap(['id' => $id, 'user_id' => $this->adminId])) {
                $this->error('没有此公众号');
            }
            return $this->show(['mp' => $mp, 'menu_title' => '修改公众号']);
        }
    }

    /**
     * 公众号列表
     * @return mixed
     * Author: fudaoji<fdj@kuryun.cn>
     */
    public function mpList()
    {
        $mp_list = model("mp")->getAll(['user_id' => $this->adminId]);
        foreach ($mp_list as $key => $v) {
            $mp_list[$key]['type'] = model('mp')->serviceTypes($v['type']);
        }
        return $this->show(['menu_title' => '公众号管理', 'mp_list' => $mp_list]);
    }
}