<?php
// +----------------------------------------------------------------------
// | [KyPHP System] Copyright (c) 2020 http://www.kuryun.com/
// +----------------------------------------------------------------------
// | [KyPHP] 并不是自由软件,你可免费使用,未经许可不能去掉KyPHP相关版权
// +----------------------------------------------------------------------
// | Author: fudaoji <fdj@kuryun.cn>
// +----------------------------------------------------------------------

/**
 * Created by PhpStorm.
 * Script Name: Material.php
 * Create: 2020/5/25 下午9:28
 * Description: frame页面获取素材
 * Author: fudaoji<fdj@kuryun.cn>
 */

namespace app\system\controller;

use app\common\model\MediaImg;
use app\common\model\Upload;

class Material extends Base
{
    /**
     * @var \think\Model
     */
    private $uploadM;
    /**
     * @var \think\Model
     */
    private $imageM;
    private $types = [
        'image', 'video', 'audio'
    ];
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->uploadM = new Upload();
        $this->imageM = new MediaImg();
        $this->assign('config', config('system.upload'));
    }

    /**
     * 素材列表
     * @return mixed
     * @author: fudaoji<fdj@kuryun.cn>
     */
    public function index(){
        $params = input();
        if(empty($params['type'])){
            $type = 'image';
        }else{
            if(in_array($params['type'], $this->types)){
                $type = $params['type'];
            }else{
                echo "type参数错误";exit;
            }
        }
        if(method_exists($this, $type)){
            return call_user_func([$this, $type]);
        }else{
            echo $type . "方法不存在";exit;
        }
    }

    /**
     * 图片
     * @return mixed
     * @author: fudaoji<fdj@kuryun.cn>
     */
    public function image(){
        $from = input('from', 'local'); //本地或微信
        $field = input('field', ''); //目标input框
        $where = ['uid' => $this->adminId];
        if($from == 'mp'){
            $data_list = $this->imageM->page(12, $where, ['id' => 'desc'], 'id,url,title', 1);
        }else{
            $data_list = $this->uploadM->page(12, $where, ['id' => 'desc'], 'id,url,original_name as title', 1);
        }
        $pager = $data_list->appends(['from' => $from])->render();
        $assign = ['data_list' => $data_list, 'pager' => $pager, 'from' => $from, 'field' => $field];
        return $this->show($assign, 'image');
    }

    /**
     * 删除图片素材
     * Author: fudaoji<fdj@kuryun.cn>
     */
    public function imageDelPost(){
        $post_data = input();
        $ids = $post_data['ids'];
        $model = $post_data['from'] == 'local' ? $this->uploadM : $this->imageM;
        foreach ($ids as $id){
            if($post_data['from'] == 'local') {
                $data = $model->getOne(['uid' => $this->adminId, 'id' => $id]);
            }
            if($model->delOne(['uid' => $this->adminId, 'id' => $id])){
                !empty($data) && @unlink($data['path']);
            }
        }
        $this->success('操作成功');
    }
}