<?php
// +----------------------------------------------------------------------
// | [KyPHP System] Copyright (c) 2020 http://www.kuryun.com/
// +----------------------------------------------------------------------
// | [KyPHP] 并不是自由软件,你可免费使用,未经许可不能去掉KyPHP相关版权
// +----------------------------------------------------------------------
// | Author: fudaoji <fdj@kuryun.cn>
// +----------------------------------------------------------------------

/**
 * Created by PhpStorm.
 * Script Name: Store.php
 * Create: 2020/5/28 下午10:57
 * Description:
 * Author: fudaoji<fdj@kuryun.cn>
 */

namespace app\system\controller;

class Store extends Base
{
    /**
     * @var \think\Model
     */
    private $storeM;
    private $storeId;
    private $storeInfo;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->storeM = model('adminStore');
        $this->storeId = (int)session('storeId');
        if($this->storeId){
            $this->storeInfo = $this->storeM->getOne($this->storeId);
        }
    }

    /**
     * 切换平台
     * @return mixed
     * @author: fudaoji<fdj@kuryun.cn>
     */
    public function index(){
        return $this->show();
    }

    /**
     * 中转
     * @author: fudaoji<fdj@kuryun.cn>
     */
    public function manage(){
        if(empty($this->storeInfo)){
            $this->redirect(url('index'));
        }else{
            $this->redirect(url($this->storeInfo['type'].'/index/index'));
        }
    }
}