<?php
// +----------------------------------------------------------------------
// | [KyPHP System] Copyright (c) 2020 http://www.kuryun.com/
// +----------------------------------------------------------------------
// | [KyPHP] 并不是自由软件,你可免费使用,未经许可不能去掉KyPHP相关版权
// +----------------------------------------------------------------------
// | Author: fudaoji <fdj@kuryun.cn>
// +----------------------------------------------------------------------

/**
 * Created by PhpStorm.
 * Script Name: Store.php
 * Create: 2020/5/28 下午10:57
 * Description: 平台、市场
 * Author: fudaoji<fdj@kuryun.cn>
 */

namespace app\system\controller;

class Store extends Base
{
    /**
     * @var \app\common\model\AdminStore
     */
    private $storeM;
    private $storeId;
    private $storeInfo;
    /**
     * @var \app\common\model\AdminAddon
     */
    private $adminAddonM;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->storeM = model('adminStore');
        $this->adminAddonM = model('adminAddon');
        $this->storeId = (int)session('storeId');
        if($this->storeId){
            $this->storeInfo = $this->storeM->getOne($this->storeId);
        }
    }

    /**
     * 切换平台
     * @return mixed
     * @throws \think\exception\DbException
     * @author: fudaoji<fdj@kuryun.cn>
     */
    public function index(){
        $type = input('type', 'all');
        $where = ['uid' => $this->adminId];
        $type !== 'all' && $where['type'] = $type;
        $data_list = $this->storeM->page($this->pageSize, $where, ['update_time' => 'desc'], true, true);
        $this->assign['page'] = $data_list->appends(['type' => $type])->render();
        foreach ($data_list as $k => $v){
            $v['data'] = model($v['type'])->getOne($v['id']);
            switch ($v['type']){
                case 'mini':
                    $v['href'] = url($v['type'].'/index/index', ['store_id' => $v['id']]);
                    break;
                default:
                    $v['href'] = url($v['type'].'/index/index', ['mid' => $v['id']]);
                    break;
            }
            $data_list[$k] = $v;
        }
        $this->assign['types'] = ['all' => '全部'] + $this->storeM->types();
        $this->assign['data_list'] = $data_list;
        $this->assign['type'] = $type;
        return $this->show();
    }

    /**
     * 中转
     * @author: fudaoji<fdj@kuryun.cn>
     */
    public function manage(){
        if(empty($this->storeInfo)){
            $this->redirect(url('index'));
        }else{
            $this->redirect(url($this->storeInfo['type'].'/index/index'));
        }
    }

    /**
     * 应用中心
     * @return mixed
     * Author: fudaoji<fdj@kuryun.cn>
     */
    public function apps(){
        return $this->show();
    }

    /**
     * 我的应用
     * @return mixed
     * Author: fudaoji<fdj@kuryun.cn>
     * @throws \think\exception\DbException
     * @throws \think\Exception
     */
    public function myApps(){
        if(request()->isPost()){ //开启关闭
            $id = input('post.id');
            $admin_addon = $this->adminAddonM->getOneByMap(['id' => $id, 'uid' => $this->adminId], true, true);
            if(empty($admin_addon)){
                $this->error('数据不存在');
            }
            $this->adminAddonM->updateOne(['id' => $id, 'status' => abs($admin_addon['status'] - 1)]);
            $this->success('操作成功');
        }

        $type = input('type', '');
        $status = input('status', -1);
        $search_key = input('search_key', '');
        $where = [
            'aa.deadline' => ['gt', time()], 'aa.uid' => $this->adminId,
        ];
        $type && $where['ad.type'] = $type;
        $status != -1 && $where['aa.status'] = $status;
        $search_key && $where['ad.name|ad.desc'] = ['like', '%'.$search_key.'%'];
        $data_list = $this->adminAddonM->pageJoin([
            'alias' => 'aa',
            'join' => [
                ['admin a', 'a.id=aa.uid'],
                ['addons ad', 'ad.addon=aa.addon']
            ],
            'order' => ['aa.update_time' => 'desc'],
            'page_size' => $this->pageSize,
            'field' => 'aa.*,a.username,a.mobile,a.realname,ad.name,ad.logo,ad.desc,ad.type',
            'refresh' => 1,
            'where' => $where
        ]);
        $page = $data_list->appends(['status' => $status, 'type' => $type, 'search_key' => $search_key])->render();

        $assign = [
            'data_list' => $data_list,
            'type' => $type,
            'search_key' => $search_key,
            'page' => $page,
            'status' => $status
        ];
        return $this->show($assign);
    }

    /**
     * 过期应用
     * @return mixed
     * Author: fudaoji<fdj@kuryun.cn>
     * @throws \think\exception\DbException
     * @throws \think\Exception
     */
    public function overtime(){
        $type = input('type', '');
        $search_key = input('search_key', '');
        $where = [
            'aa.deadline' => ['lt', time()], 'aa.uid' => $this->adminId,
        ];
        $type && $where['ad.type'] = $type;
        $search_key && $where['ad.name|ad.desc'] = ['like', '%'.$search_key.'%'];
        $data_list = $this->adminAddonM->pageJoin([
            'alias' => 'aa',
            'join' => [
                ['admin a', 'a.id=aa.uid'],
                ['addons ad', 'ad.addon=aa.addon']
            ],
            'order' => ['aa.update_time' => 'desc'],
            'page_size' => $this->pageSize,
            'field' => 'aa.*,a.username,a.mobile,a.realname,ad.name,ad.logo,ad.desc,ad.type',
            'refresh' => 1,
            'where' => $where
        ]);
        $page = $data_list->appends(['type' => $type, 'search_key' => $search_key])->render();

        $assign = [
            'data_list' => $data_list,
            'type' => $type,
            'search_key' => $search_key,
            'page' => $page
        ];
        return $this->show($assign);
    }
}